# Generated by Django 5.2.9 on 2025-12-29 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('plan', models.CharField(choices=[('freemium', 'Freemium'), ('standard', 'Standard'), ('pro', 'Pro')], db_index=True, default='freemium', max_length=20)),
                ('flutterwave_customer_id', models.CharField(blank=True, max_length=255)),
                ('n8n_webhook_url', models.URLField(blank=True)),
                ('leads_quota', models.PositiveIntegerField(default=3)),
                ('brand_logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#0A0F1A', max_length=16)),
                ('secondary_color', models.CharField(default='#1F6BFF', max_length=16)),
                ('widget_theme', models.CharField(choices=[('frosted', 'Frosted Glass (Light)'), ('smoked', 'Smoked Glass (Dark)')], default='frosted', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
