# Generated by Django 5.2.9 on 2025-12-29 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('good', 'Good'), ('better', 'Better'), ('best', 'Best')], max_length=12)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=8)),
                ('zip_code', models.CharField(blank=True, max_length=16)),
                ('sourced_via', models.CharField(default='manual', max_length=32)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_rates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.tenant')),
            ],
            options={
                'verbose_name': 'Material Rate',
                'verbose_name_plural': 'Material Rates',
                'indexes': [models.Index(fields=['tenant', 'tier'], name='pricing_mat_tenant__c10ece_idx'), models.Index(fields=['tenant', 'zip_code'], name='pricing_mat_tenant__0e6833_idx')],
                'unique_together': {('tenant', 'contractor', 'tier', 'zip_code')},
            },
        ),
    ]
