# Generated by Django 5.2.9 on 2025-12-31 15:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_tool_coupon_code_tool_coupon_end_and_more'),
        ('pricing', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('material_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('labor_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.tenant')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_settings', to='marketplace.tool')),
            ],
            options={
                'verbose_name': 'Material Setting',
                'verbose_name_plural': 'Material Settings',
                'unique_together': {('tenant', 'tool', 'name')},
            },
        ),
    ]
