# Generated by Django 5.2.9 on 2025-12-29 11:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True)),
                ('media_url', models.URLField(blank=True, help_text='Looping mp4/gif for hero section previews')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
                ('bento_features', models.JSONField(blank=True, default=list, help_text='List of feature cards for bento layout; shape: [{title, copy, icon}]')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_color', models.CharField(default='#0A0F1A', max_length=16)),
                ('secondary_color', models.CharField(default='#1F6BFF', max_length=16)),
                ('theme', models.CharField(choices=[('frosted', 'Frosted Glass (Light)'), ('smoked', 'Smoked Glass (Dark)')], default='frosted', max_length=16)),
                ('logo_url', models.URLField(blank=True)),
                ('mark_text', models.CharField(default='neX', help_text='Watermark shown in widget corner', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.tenant')),
            ],
            options={
                'verbose_name': 'Widget Config',
                'verbose_name_plural': 'Widget Configs',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceLead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('source', models.CharField(default='landing', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_leads', to='shared.tenant')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='marketplace.tool')),
            ],
            options={
                'verbose_name': 'Marketplace Lead',
                'verbose_name_plural': 'Marketplace Leads',
                'indexes': [models.Index(fields=['email'], name='marketplace_email_42695a_idx')],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('trial', 'Trial'), ('pending', 'Pending')], db_index=True, default='trial', max_length=16)),
                ('plan', models.CharField(default='standard', max_length=32)),
                ('seats', models.PositiveIntegerField(default=1)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.tenant')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='marketplace.tool')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'indexes': [models.Index(fields=['tenant', 'status'], name='marketplace_tenant__884610_idx')],
                'unique_together': {('tenant', 'tool')},
            },
        ),
        migrations.CreateModel(
            name='WidgetLead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('estimate_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ground_area', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pitch', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('actual_area', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('source_url', models.URLField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.tenant')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widget_leads', to='marketplace.tool')),
            ],
            options={
                'verbose_name': 'Widget Lead',
                'verbose_name_plural': 'Widget Leads',
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='marketplace_tenant__495725_idx')],
            },
        ),
    ]
