# Generated by Django 5.2.9 on 2025-12-31 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tool',
            name='coupon_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='coupon_percent_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tool',
            name='coupon_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='coupon_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_coupons', to='shared.tenant'),
        ),
        migrations.AddField(
            model_name='tool',
            name='coupon_usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='coupon_usage_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='marketing_hook',
            field=models.CharField(default='See Your Roof from Space & Get a Technical Estimate in 60 Seconds.', max_length=255),
        ),
    ]
