# Generated by Django 5.2.9 on 2025-12-29 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('zip_code', models.CharField(max_length=16)),
                ('roof_type', models.CharField(blank=True, max_length=32)),
                ('pitch', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('base_area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_good', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_better', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_best', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscription_tier', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], db_index=True, default='new', max_length=20)),
                ('locked_for_quota', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.tenant')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'indexes': [models.Index(fields=['tenant', 'status'], name='leads_lead_tenant__054659_idx'), models.Index(fields=['tenant', 'created_at'], name='leads_lead_tenant__5e5f75_idx')],
            },
        ),
    ]
